import type { ComponentType } from 'react'

import {
  Crop,
  FileImage,
  FileSearch,
  FileText,
  Files,
  Image,
  Languages,
  Lock,
  Minimize2,
  Package,
  Palette,
  PenTool,
  QrCode,
  RotateCw,
  Scissors,
  Search,
  Shield,
  Sparkles,
  Type,
  Unlock,
  Wand2,
} from 'lucide-react'

const iconMap: Record<string, ComponentType<{ className?: string }>> = {
  'merge-pdf': Files,
  'split-pdf': Scissors,
  'compress-pdf': Minimize2,
  'rotate-pdf': RotateCw,
  'organize-pdf': Package,
  'crop-pdf': Crop,
  'watermark-pdf': PenTool,
  'page-numbers-pdf': Type,
  'protect-pdf': Lock,
  'unlock-pdf': Unlock,
  'redact-pdf': Shield,
  'compare-pdf': Search,
  'extract-text-pdf': FileText,
  'extract-images-pdf': FileImage,
  'pdf-to-jpg': Image,
  'pdf-to-png': Image,
  'jpg-to-pdf': FileImage,
  'image-to-pdf': FileImage,
  'repair-pdf': Wand2,
  'translate-pdf': Languages,
  'summarize-pdf': Sparkles,
  'pdf-to-docx': FileText,
  'docx-to-pdf': FileText,
  'pdf-to-excel': FileSearch,
  'excel-to-pdf': FileSearch,
  'pdf-to-pptx': Files,
  'pptx-to-pdf': Files,
  'scan-to-pdf': FileImage,
  'sign-pdf': PenTool,
  'edit-metadata-pdf': FileSearch,
  'pdf-to-pdfa': FileText,
  'chat-with-pdf': Sparkles,
  'ocr-image': Search,
  'ocr-pdf': Search,
  'remove-background': Wand2,
  'blur-background': Wand2,
  'blur-face': Shield,
  'pixelate-face': Shield,
  'add-text-image': Type,
  'add-logo-image': FileImage,
  'join-images': Files,
  'split-image': Scissors,
  'circle-crop-image': Crop,
  'square-crop-image': Crop,
  'image-color-picker': Palette,
  'motion-blur-image': Sparkles,
  'compress-image': Minimize2,
  'resize-image': Crop,
  'crop-image': Crop,
  'rotate-image': RotateCw,
  'convert-image': Image,
  'watermark-image': PenTool,
  'grayscale-image': Palette,
  'blur-image': Wand2,
  'pixelate-image': Sparkles,
  'meme-generator': Type,
  'upscale-image': Image,
  'pdf-to-image': FileImage,
  'pdf-to-tiff': FileImage,
  'tiff-to-pdf': FileImage,
  'pdf-to-svg': FileImage,
  'svg-to-pdf': FileImage,
  'html-to-pdf': FileText,
  'md-to-pdf': FileText,
  'txt-to-pdf': FileText,
  'summarize-text': Sparkles,
  'translate-text': Languages,
  'qr-code-generator': QrCode,
  'extract-metadata': FileSearch,
  'remove-metadata-image': Shield,
  'extract-pages': Scissors,
  'delete-pages': Scissors,
  'rearrange-pages': Package,
  'add-text-pdf': Type,
  'header-footer-pdf': Type,
  'resize-pages-pdf': Crop,
  'remove-metadata-pdf': Shield,
  'whiteout-pdf': Shield,
  'grayscale-pdf': Palette,
  'create-pdf': FileText,
  'url-to-pdf': FileText,
  'png-to-pdf': FileImage,
  'webp-to-pdf': FileImage,
  'gif-to-pdf': FileImage,
  'bmp-to-pdf': FileImage,
  'jpg-to-png': Image,
  'png-to-jpg': Image,
  'image-to-webp': Image,
  'pdf-to-txt': FileText,
  'pdf-to-markdown': FileText,
  'pdf-to-json': FileSearch,
  'pdf-to-csv': FileSearch,
  'json-to-pdf': FileText,
  'xml-to-pdf': FileText,
  'csv-to-pdf': FileText,
  'pdf-to-rtf': FileText,
  'rtf-to-pdf': FileText,
  'pdf-to-odt': FileText,
  'odt-to-pdf': FileText,
  'pdf-to-epub': FileText,
  'epub-to-pdf': FileText,
  'flip-image': RotateCw,
  'add-border-image': Crop,
  'thumbnail-image': Image,
  'image-collage': Files,
  'word-count-text': FileSearch,
  'case-converter-text': Type,
  'extract-keywords-text': Search,
  'slug-generator-text': FileText,
  'create-workflow': Package,
  'add-image-pdf': FileImage,
  'pdf-pages-to-zip': Package,
  'zip-images-to-pdf': Package,
  'pdf-page-count': FileSearch,
  'reverse-pdf': RotateCw,
  'flatten-pdf': Shield,
  'pdf-to-html': FileText,
  'pdf-to-bmp': FileImage,
  'pdf-to-gif': FileImage,
  'sharpen-image': Sparkles,
  'brighten-image': Sparkles,
  'contrast-image': Palette,
  'invert-image': Palette,
  'posterize-image': Wand2,
  'image-histogram': FileSearch,
  'remove-extra-spaces-text': Type,
  'sort-lines-text': Type,
  'deduplicate-lines-text': Type,
  'find-replace-text': Search,
  'split-text-file': Scissors,
  'reading-time-text': FileSearch,
  'images-to-zip': Package,
  'batch-convert-images': Image,
  'merge-text-files': Files,
  'json-prettify': FileSearch,
  'csv-to-json': FileSearch,
  'json-to-csv': FileSearch,
}

type ToolIconProps = {
  slug: string
  className?: string
}

export default function ToolIcon({ slug, className }: ToolIconProps) {
  const Icon = iconMap[slug] || FileText
  return <Icon className={className} />
}
