import type { ComponentType } from 'react'

import {
  Crop,
  FileImage,
  FileSearch,
  FileText,
  Files,
  Image,
  Languages,
  Lock,
  Minimize2,
  Package,
  Palette,
  PenTool,
  QrCode,
  RotateCw,
  Scissors,
  Search,
  Shield,
  Sparkles,
  Type,
  Unlock,
  Wand2,
} from 'lucide-react'

const iconMap: Record<string, ComponentType<{ className?: string }>> = {
  'merge-pdf': Files,
  'split-pdf': Scissors,
  'compress-pdf': Minimize2,
  'optimize-pdf': Minimize2,
  'rotate-pdf': RotateCw,
  'organize-pdf': Package,
  'edit-pdf': PenTool,
  'annotate-pdf': PenTool,
  'highlight-pdf': Palette,
  'pdf-filler': Type,
  'crop-pdf': Crop,
  'watermark-pdf': PenTool,
  'add-watermark': PenTool,
  'page-numbers-pdf': Type,
  'add-page-numbers': Type,
  'protect-pdf': Lock,
  'pdf-security': Shield,
  'unlock-pdf': Unlock,
  'redact-pdf': Shield,
  'compare-pdf': Search,
  'extract-text-pdf': FileText,
  'extract-images-pdf': FileImage,
  'pdf-viewer': FileSearch,
  'pdf-intelligence': Sparkles,
  'pdf-ocr': Search,
  'convert-to-pdf': FileText,
  'convert-from-pdf': FileText,
  'pdf-converter': Files,
  'pdf-to-jpg': Image,
  'pdf-to-png': Image,
  'pdf-to-word': FileText,
  'word-to-pdf': FileText,
  'pdf-to-powerpoint': Files,
  'powerpoint-to-pdf': Files,
  'jpg-to-pdf': FileImage,
  'heic-to-pdf': FileImage,
  'heif-to-pdf': FileImage,
  'jfif-to-pdf': FileImage,
  'image-to-pdf': FileImage,
  'repair-pdf': Wand2,
  'translate-pdf': Languages,
  'summarize-pdf': Sparkles,
  'ai-summarizer': Sparkles,
  'pdf-to-docx': FileText,
  'docx-to-pdf': FileText,
  'pdf-to-excel': FileSearch,
  'excel-to-pdf': FileSearch,
  'pdf-to-pptx': Files,
  'pptx-to-pdf': Files,
  'scan-to-pdf': FileImage,
  'sign-pdf': PenTool,
  'edit-metadata-pdf': FileSearch,
  'pdf-to-pdfa': FileText,
  'chat-with-pdf': Sparkles,
  'ocr-image': Search,
  'image-to-text': Search,
  'jpg-to-text': Search,
  'png-to-text': Search,
  'ocr-pdf': Search,
  'remove-background': Wand2,
  'remove-image-object': Wand2,
  'blur-background': Wand2,
  'blur-face': Shield,
  'unblur-face': Sparkles,
  'pixelate-face': Shield,
  'add-text-image': Type,
  'add-logo-image': FileImage,
  'join-images': Files,
  'split-image': Scissors,
  'image-splitter': Scissors,
  'circle-crop-image': Crop,
  'square-crop-image': Crop,
  'image-color-picker': Palette,
  'motion-blur-image': Sparkles,
  'compress-image': Minimize2,
  'resize-image': Crop,
  'resize-image-pixel': Crop,
  'resize-image-in-cm': Crop,
  'resize-image-in-mm': Crop,
  'resize-image-in-inch': Crop,
  'resize-signature': Crop,
  'resize-image-to-3.5cmx4.5cm': Crop,
  'resize-image-to-6cmx2cm': Crop,
  'resize-signature-to-50mmx20mm': Crop,
  'resize-image-to-35mmx45mm': Crop,
  'resize-image-to-2x2': Crop,
  'resize-image-to-3x4': Crop,
  'resize-image-to-4x6': Crop,
  'resize-image-to-600x600-pixel': Crop,
  'resize-image-for-whatsapp-dp': Crop,
  'resize-image-for-youtube-banner': Crop,
  'resize-image-to-a4-size': Crop,
  'crop-image': Crop,
  'rotate-image': RotateCw,
  'convert-image': Image,
  'convert-dpi': FileSearch,
  'check-image-dpi': FileSearch,
  'watermark-image': PenTool,
  'add-name-dob-image': Type,
  'merge-photo-signature': Files,
  'grayscale-image': Palette,
  'black-and-white-image': Palette,
  'blur-image': Wand2,
  'pixelate-image': Sparkles,
  'picture-to-pixel-art': Sparkles,
  'censor-photo': Shield,
  'meme-generator': Type,
  'generate-signature': PenTool,
  'upscale-image': Image,
  'pdf-to-image': FileImage,
  'pdf-to-tiff': FileImage,
  'tiff-to-pdf': FileImage,
  'pdf-to-svg': FileImage,
  'svg-to-pdf': FileImage,
  'html-to-pdf': FileText,
  'md-to-pdf': FileText,
  'txt-to-pdf': FileText,
  'summarize-text': Sparkles,
  'translate-text': Languages,
  'qr-code-generator': QrCode,
  'extract-metadata': FileSearch,
  'remove-metadata-image': Shield,
  'remove-image-metadata': Shield,
  'extract-pages': Scissors,
  'delete-pages': Scissors,
  'rearrange-pages': Package,
  'add-text-pdf': Type,
  'header-footer-pdf': Type,
  'resize-pages-pdf': Crop,
  'remove-metadata-pdf': Shield,
  'whiteout-pdf': Shield,
  'grayscale-pdf': Palette,
  'create-pdf': FileText,
  'url-to-pdf': FileText,
  'png-to-pdf': FileImage,
  'webp-to-pdf': FileImage,
  'gif-to-pdf': FileImage,
  'bmp-to-pdf': FileImage,
  'jpg-to-png': Image,
  'jpeg-to-png': Image,
  'png-to-jpg': Image,
  'png-to-jpeg': Image,
  'image-to-webp': Image,
  'pdf-to-txt': FileText,
  'pdf-to-markdown': FileText,
  'pdf-to-json': FileSearch,
  'pdf-to-csv': FileSearch,
  'json-to-pdf': FileText,
  'xml-to-pdf': FileText,
  'csv-to-pdf': FileText,
  'pdf-to-rtf': FileText,
  'rtf-to-pdf': FileText,
  'pdf-to-odt': FileText,
  'odt-to-pdf': FileText,
  'pdf-to-epub': FileText,
  'epub-to-pdf': FileText,
  'flip-image': RotateCw,
  'add-border-image': Crop,
  'thumbnail-image': Image,
  'image-collage': Files,
  'word-count-text': FileSearch,
  'case-converter-text': Type,
  'extract-keywords-text': Search,
  'slug-generator-text': FileText,
  'create-workflow': Package,
  'add-image-pdf': FileImage,
  'pdf-pages-to-zip': Package,
  'zip-images-to-pdf': Package,
  'zip-to-pdf': Package,
  'pdf-page-count': FileSearch,
  'reverse-pdf': RotateCw,
  'flatten-pdf': Shield,
  'pdf-to-html': FileText,
  'pdf-to-bmp': FileImage,
  'pdf-to-gif': FileImage,
  'eml-to-pdf': FileText,
  'fb2-to-pdf': FileText,
  'cbz-to-pdf': Package,
  'ebook-to-pdf': FileText,
  'sharpen-image': Sparkles,
  'brighten-image': Sparkles,
  'contrast-image': Palette,
  'invert-image': Palette,
  'posterize-image': Wand2,
  'image-histogram': FileSearch,
  'remove-extra-spaces-text': Type,
  'sort-lines-text': Type,
  'deduplicate-lines-text': Type,
  'find-replace-text': Search,
  'split-text-file': Scissors,
  'reading-time-text': FileSearch,
  'images-to-zip': Package,
  'batch-convert-images': Image,
  'merge-text-files': Files,
  'json-prettify': FileSearch,
  'csv-to-json': FileSearch,
  'json-to-csv': FileSearch,
  'a4-size-resize': Crop,
  'add-white-border-image': Crop,
  'ai-to-pdf': FileText,
  'beautify-image': Sparkles,
  'cbr-to-pdf': Package,
  'check-dpi': FileSearch,
  'chm-to-pdf': FileText,
  'color-code-from-image': Palette,
  'compress-to-5kb': Minimize2,
  'compress-to-10kb': Minimize2,
  'compress-to-15kb': Minimize2,
  'compress-to-20kb': Minimize2,
  'compress-to-25kb': Minimize2,
  'compress-to-30kb': Minimize2,
  'compress-to-40kb': Minimize2,
  'compress-to-50kb': Minimize2,
  'compress-to-100kb': Minimize2,
  'compress-to-150kb': Minimize2,
  'compress-to-200kb': Minimize2,
  'compress-to-300kb': Minimize2,
  'compress-to-500kb': Minimize2,
  'compress-to-1mb': Minimize2,
  'compress-to-2mb': Minimize2,
  'compress-to-kb': Minimize2,
  'increase-image-size-in-kb': Minimize2,
  'reduce-image-size-in-mb': Minimize2,
  'convert-image-from-mb-to-kb': Minimize2,
  'convert-image-size-kb-to-mb': Minimize2,
  'jpg-to-kb': Minimize2,
  'jpeg-to-jpg': Image,
  'jpg-to-pdf-under-50kb': FileImage,
  'jpg-to-pdf-under-100kb': FileImage,
  'jpeg-to-pdf-under-200kb': FileImage,
  'jpg-to-pdf-under-300kb': FileImage,
  'jpg-to-pdf-under-500kb': FileImage,
  'convert-from-jpg': Image,
  'convert-to-jpg': Image,
  'crop-png': Crop,
  'djvu-to-pdf': FileText,
  'dwg-to-pdf': FileImage,
  'dxf-to-pdf': FileImage,
  'freehand-crop': Crop,
  'heic-to-jpg': Image,
  'html-to-image': Image,
  'hwp-to-pdf': FileText,
  'increase-image-quality': Sparkles,
  'instagram-grid': Scissors,
  'mobi-to-pdf': FileText,
  'pages-to-pdf': FileText,
  'passport-photo-maker': Crop,
  'passport-size-photo': Crop,
  'pdf-to-mobi': FileText,
  'photo-editor': Wand2,
  'pub-to-pdf': FileText,
  'reduce-image-size-in-kb': Minimize2,
  'resize-for-instagram': Crop,
  'resize-for-whatsapp': Crop,
  'resize-for-youtube': Crop,
  'retouch-image': Sparkles,
  'social-media-resize': Crop,
  'super-resolution': Sparkles,
  'unblur-image': Sparkles,
  'view-metadata': FileSearch,
  'webp-to-jpg': Image,
  'wps-to-pdf': FileText,
  'xps-to-pdf': FileText,
  'zoom-out-image': Crop,
  'remove-pages': Scissors,
  'edit-metadata': FileSearch,
}

type ToolIconProps = {
  slug: string
  className?: string
}

function pickFallbackIcon(slug: string): ComponentType<{ className?: string }> {
  const value = slug.toLowerCase()

  if (/compress|minify|reduce|optimize|\bkb\b|\bmb\b/.test(value)) return Minimize2
  if (/merge|join|combine/.test(value)) return Files
  if (/split|extract|crop|cut/.test(value)) return Scissors
  if (/rotate|flip/.test(value)) return RotateCw
  if (/lock|protect|unlock|security|redact|whiteout/.test(value)) return Shield
  if (/watermark|signature|sign|annotate|highlight|filler|edit/.test(value)) return PenTool
  if (/translate|language/.test(value)) return Languages
  if (/ocr|scan|search/.test(value)) return Search
  if (/ai|summar|intelligence|chat|enhance|upscale|beautify|retouch/.test(value)) return Sparkles
  if (/qr/.test(value)) return QrCode
  if (/jpg|jpeg|png|webp|gif|bmp|tiff|heic|heif|image/.test(value)) return Image
  if (/pdf|docx|word|pptx|excel|xlsx|json|csv|xml|txt|md|rtf|odt|epub|mobi/.test(value)) return FileText

  return FileText
}

export default function ToolIcon({ slug, className }: ToolIconProps) {
  const Icon = iconMap[slug] || pickFallbackIcon(slug)
  return <Icon className={className} />
}
