from .models import ToolCategory, ToolDefinition

CATEGORIES: list[ToolCategory] = [
    ToolCategory(
        id="pdf-core",
        label="PDF Core",
        description="Merge, split, convert, and optimize PDFs for daily workflows.",
    ),
    ToolCategory(
        id="pdf-security",
        label="PDF Security",
        description="Protect, unlock, and redact files safely.",
    ),
    ToolCategory(
        id="pdf-advanced",
        label="PDF Advanced",
        description="Page organization, comparison, translation, and metadata flows.",
    ),
    ToolCategory(
        id="image-core",
        label="Image Essentials",
        description="Compress, resize, crop, rotate, and convert images in bulk.",
    ),
    ToolCategory(
        id="image-effects",
        label="Image Effects",
        description="Watermarking, blur, grayscale, pixelate, meme, and styling tools.",
    ),
    ToolCategory(
        id="document-convert",
        label="Document Convert",
        description="Turn text, HTML, and markdown content into PDFs.",
    ),
    ToolCategory(
        id="office-suite",
        label="Office Suite",
        description="Convert between PDF and DOCX, PPTX, XLSX formats for office workflows.",
    ),
    ToolCategory(
        id="text-ai",
        label="Text and AI Utilities",
        description="Summarize and translate text or PDF content.",
    ),
    ToolCategory(
        id="utility",
        label="Utility Lab",
        description="Extra productivity helpers like QR generation and metadata tools.",
    ),
    ToolCategory(
        id="page-ops",
        label="Page Operations",
        description="Extract, delete, reorder, and resize PDF pages quickly.",
    ),
    ToolCategory(
        id="format-lab",
        label="Format Lab",
        description="Extended format conversion tools for image and PDF workflows.",
    ),
    ToolCategory(
        id="data-tools",
        label="Data and Export",
        description="Export PDF/text content into TXT, CSV, JSON, and Markdown formats.",
    ),
    ToolCategory(
        id="image-layout",
        label="Image Layout Studio",
        description="Flip, add borders, generate thumbnails, and build collages.",
    ),
    ToolCategory(
        id="text-ops",
        label="Text Operations",
        description="Word analytics, case conversion, keyword extraction, and slug generation.",
    ),
    ToolCategory(
        id="archive-lab",
        label="Archive Workflows",
        description="ZIP-oriented tools for image and PDF batch workflows.",
    ),
    ToolCategory(
        id="pdf-insights",
        label="PDF Insights",
        description="Analyze, flatten, reorder, and export PDF content into more formats.",
    ),
    ToolCategory(
        id="image-enhance",
        label="Image Enhancement",
        description="Sharpen, brighten, contrast, invert, and analyze image quality quickly.",
    ),
    ToolCategory(
        id="text-cleanup",
        label="Text Cleanup",
        description="Clean, sort, deduplicate, and transform text files for production use.",
    ),
    ToolCategory(
        id="batch-automation",
        label="Batch Automation",
        description="Batch zip, conversion, merge, and JSON/CSV automation workflows.",
    ),
    ToolCategory(
        id="ocr-vision",
        label="OCR and Vision AI",
        description="OCR, face blur, and background cleanup workflows for scanned files and images.",
    ),
    ToolCategory(
        id="ebook-convert",
        label="eBook and Rich Text",
        description="Convert between PDF, EPUB, ODT, and RTF document formats.",
    ),
    ToolCategory(
        id="vector-lab",
        label="Vector and Scan Formats",
        description="Convert SVG, TIFF, and scan-heavy assets into more usable outputs.",
    ),
]

TOOLS: list[ToolDefinition] = [
    ToolDefinition(
        slug="merge-pdf",
        title="Merge PDF",
        description="Combine multiple PDF files in chosen order.",
        category="pdf-core",
        tags=["merge", "combine", "pdf"],
        input_kind="files",
        accepts_multiple=True,
    ),
    ToolDefinition(
        slug="split-pdf",
        title="Split PDF",
        description="Split one PDF into separate page files.",
        category="pdf-core",
        tags=["split", "pages", "pdf"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="compress-pdf",
        title="Compress PDF",
        description="Reduce PDF size using stream compression.",
        category="pdf-core",
        tags=["compress", "optimize", "pdf"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="rotate-pdf",
        title="Rotate PDF",
        description="Rotate all pages in a PDF.",
        category="pdf-core",
        tags=["rotate", "pdf", "orientation"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="organize-pdf",
        title="Organize PDF",
        description="Reorder pages using a custom page sequence.",
        category="pdf-advanced",
        tags=["reorder", "organize", "pdf"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="crop-pdf",
        title="Crop PDF",
        description="Crop margins of all pages by custom values.",
        category="pdf-advanced",
        tags=["crop", "pdf", "margins"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="watermark-pdf",
        title="Watermark PDF",
        description="Add text watermark to each page.",
        category="pdf-core",
        tags=["watermark", "branding", "pdf"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="page-numbers-pdf",
        title="Page Numbers",
        description="Insert page numbers at top or bottom positions.",
        category="pdf-advanced",
        tags=["page numbers", "pdf"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="protect-pdf",
        title="Protect PDF",
        description="Encrypt PDF with a password.",
        category="pdf-security",
        tags=["password", "encrypt", "pdf"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="unlock-pdf",
        title="Unlock PDF",
        description="Remove password from protected PDF.",
        category="pdf-security",
        tags=["unlock", "decrypt", "pdf"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="redact-pdf",
        title="Redact PDF",
        description="Find and blackout specific keywords.",
        category="pdf-security",
        tags=["redact", "privacy", "pdf"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="compare-pdf",
        title="Compare PDF",
        description="Compare text between two PDFs and generate diff output.",
        category="pdf-advanced",
        tags=["compare", "diff", "pdf"],
        input_kind="files",
        accepts_multiple=True,
    ),
    ToolDefinition(
        slug="extract-text-pdf",
        title="Extract Text",
        description="Extract all text content from a PDF file.",
        category="pdf-advanced",
        tags=["extract", "text", "pdf"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="extract-images-pdf",
        title="Extract Images",
        description="Extract embedded images from a PDF.",
        category="pdf-advanced",
        tags=["extract", "images", "pdf"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="pdf-to-jpg",
        title="PDF to JPG",
        description="Render each PDF page into JPG files.",
        category="pdf-core",
        tags=["convert", "pdf", "jpg"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="pdf-to-png",
        title="PDF to PNG",
        description="Render each PDF page into PNG files.",
        category="pdf-core",
        tags=["convert", "pdf", "png"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="jpg-to-pdf",
        title="JPG to PDF",
        description="Convert multiple images into one PDF.",
        category="pdf-core",
        tags=["convert", "jpg", "pdf"],
        input_kind="files",
        accepts_multiple=True,
    ),
    ToolDefinition(
        slug="image-to-pdf",
        title="Image to PDF",
        description="Convert mixed image formats into one PDF.",
        category="pdf-core",
        tags=["image", "convert", "pdf"],
        input_kind="files",
        accepts_multiple=True,
    ),
    ToolDefinition(
        slug="repair-pdf",
        title="Repair PDF",
        description="Attempt to rebuild and repair a damaged PDF structure.",
        category="pdf-advanced",
        tags=["repair", "recover", "pdf"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="translate-pdf",
        title="Translate PDF",
        description="Extract and translate PDF text into a selected language.",
        category="text-ai",
        tags=["translate", "pdf", "ai"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="summarize-pdf",
        title="Summarize PDF",
        description="Generate concise summary from PDF text.",
        category="text-ai",
        tags=["summary", "pdf", "ai"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="compress-image",
        title="Compress Image",
        description="Compress JPG, PNG, and WebP images.",
        category="image-core",
        tags=["compress", "image", "optimize"],
        input_kind="files",
        accepts_multiple=True,
    ),
    ToolDefinition(
        slug="resize-image",
        title="Resize Image",
        description="Resize image by width and height.",
        category="image-core",
        tags=["resize", "image"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="crop-image",
        title="Crop Image",
        description="Crop image using x/y/width/height values.",
        category="image-core",
        tags=["crop", "image"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="rotate-image",
        title="Rotate Image",
        description="Rotate image by any angle.",
        category="image-core",
        tags=["rotate", "image"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="convert-image",
        title="Convert Image",
        description="Convert image between JPG, PNG, WEBP, and GIF.",
        category="image-core",
        tags=["convert", "image", "format"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="watermark-image",
        title="Watermark Image",
        description="Overlay custom text watermark on image.",
        category="image-effects",
        tags=["watermark", "image", "branding"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="grayscale-image",
        title="Grayscale Image",
        description="Convert image into grayscale mode.",
        category="image-effects",
        tags=["grayscale", "image", "effect"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="blur-image",
        title="Blur Image",
        description="Apply gaussian blur to an image.",
        category="image-effects",
        tags=["blur", "image"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="pixelate-image",
        title="Pixelate Image",
        description="Apply pixel-art style pixelation.",
        category="image-effects",
        tags=["pixelate", "image", "effect"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="meme-generator",
        title="Meme Generator",
        description="Add top and bottom meme text to image.",
        category="image-effects",
        tags=["meme", "text", "image"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="pdf-to-image",
        title="PDF to Image",
        description="Export PDF pages as images.",
        category="document-convert",
        tags=["pdf", "image", "convert"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="html-to-pdf",
        title="HTML to PDF",
        description="Convert URL or HTML text into a PDF report.",
        category="document-convert",
        tags=["html", "url", "pdf"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="md-to-pdf",
        title="MD to PDF",
        description="Convert markdown content into PDF.",
        category="document-convert",
        tags=["markdown", "pdf", "convert"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="txt-to-pdf",
        title="TXT to PDF",
        description="Convert text files into PDF documents.",
        category="document-convert",
        tags=["txt", "pdf", "convert"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="summarize-text",
        title="Summarize Text",
        description="Generate short summary from long text.",
        category="text-ai",
        tags=["summary", "text", "ai"],
        input_kind="text",
    ),
    ToolDefinition(
        slug="translate-text",
        title="Translate Text",
        description="Translate text into target language.",
        category="text-ai",
        tags=["translate", "text", "language"],
        input_kind="text",
    ),
    ToolDefinition(
        slug="qr-code-generator",
        title="QR Code Generator",
        description="Generate QR code image from URL or text.",
        category="utility",
        tags=["qr", "utility", "image"],
        input_kind="text",
    ),
    ToolDefinition(
        slug="extract-metadata",
        title="Extract Metadata",
        description="Read metadata from PDF or image files.",
        category="utility",
        tags=["metadata", "pdf", "image"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="remove-metadata-image",
        title="Remove Image Metadata",
        description="Strip EXIF metadata from images.",
        category="utility",
        tags=["metadata", "exif", "privacy"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="extract-pages",
        title="Extract Pages",
        description="Extract selected pages into separate PDF files.",
        category="page-ops",
        tags=["extract", "pages", "pdf"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="delete-pages",
        title="Delete Pages",
        description="Delete selected pages from a PDF document.",
        category="page-ops",
        tags=["delete", "pages", "pdf"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="rearrange-pages",
        title="Rearrange Pages",
        description="Rearrange page order of a PDF file.",
        category="page-ops",
        tags=["rearrange", "pages", "pdf"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="add-text-pdf",
        title="Add Text PDF",
        description="Overlay custom text on each page.",
        category="page-ops",
        tags=["text", "overlay", "pdf"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="header-footer-pdf",
        title="Header and Footer",
        description="Add header and footer text to all pages.",
        category="page-ops",
        tags=["header", "footer", "pdf"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="resize-pages-pdf",
        title="Resize Pages",
        description="Scale all pages by a custom factor.",
        category="page-ops",
        tags=["resize", "pages", "pdf"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="remove-metadata-pdf",
        title="Remove PDF Metadata",
        description="Remove metadata from PDF file.",
        category="pdf-security",
        tags=["metadata", "privacy", "pdf"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="whiteout-pdf",
        title="Whiteout PDF",
        description="Whiteout selected keywords in a PDF.",
        category="pdf-security",
        tags=["whiteout", "privacy", "pdf"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="grayscale-pdf",
        title="Grayscale PDF",
        description="Convert PDF pages to grayscale.",
        category="pdf-advanced",
        tags=["grayscale", "pdf", "convert"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="create-pdf",
        title="Create PDF",
        description="Create a fresh PDF from plain text.",
        category="document-convert",
        tags=["create", "pdf", "text"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="url-to-pdf",
        title="URL to PDF",
        description="Convert webpage URL into PDF report.",
        category="document-convert",
        tags=["url", "pdf", "convert"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="png-to-pdf",
        title="PNG to PDF",
        description="Convert PNG files into one PDF.",
        category="format-lab",
        tags=["png", "pdf", "convert"],
        input_kind="files",
        accepts_multiple=True,
    ),
    ToolDefinition(
        slug="webp-to-pdf",
        title="WEBP to PDF",
        description="Convert WEBP files into one PDF.",
        category="format-lab",
        tags=["webp", "pdf", "convert"],
        input_kind="files",
        accepts_multiple=True,
    ),
    ToolDefinition(
        slug="gif-to-pdf",
        title="GIF to PDF",
        description="Convert GIF files into one PDF.",
        category="format-lab",
        tags=["gif", "pdf", "convert"],
        input_kind="files",
        accepts_multiple=True,
    ),
    ToolDefinition(
        slug="bmp-to-pdf",
        title="BMP to PDF",
        description="Convert BMP files into one PDF.",
        category="format-lab",
        tags=["bmp", "pdf", "convert"],
        input_kind="files",
        accepts_multiple=True,
    ),
    ToolDefinition(
        slug="jpg-to-png",
        title="JPG to PNG",
        description="Convert JPG images into PNG format.",
        category="format-lab",
        tags=["jpg", "png", "convert"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="png-to-jpg",
        title="PNG to JPG",
        description="Convert PNG images into JPG format.",
        category="format-lab",
        tags=["png", "jpg", "convert"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="image-to-webp",
        title="Image to WEBP",
        description="Convert image files into WEBP format.",
        category="format-lab",
        tags=["image", "webp", "convert"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="pdf-to-txt",
        title="PDF to TXT",
        description="Export PDF text as plain TXT file.",
        category="data-tools",
        tags=["pdf", "txt", "export"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="pdf-to-markdown",
        title="PDF to Markdown",
        description="Export PDF content into markdown format.",
        category="data-tools",
        tags=["pdf", "markdown", "export"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="pdf-to-json",
        title="PDF to JSON",
        description="Export PDF text and metadata into JSON.",
        category="data-tools",
        tags=["pdf", "json", "export"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="pdf-to-csv",
        title="PDF to CSV",
        description="Export PDF text lines into CSV table.",
        category="data-tools",
        tags=["pdf", "csv", "export"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="json-to-pdf",
        title="JSON to PDF",
        description="Convert JSON text/file into PDF document.",
        category="data-tools",
        tags=["json", "pdf", "convert"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="xml-to-pdf",
        title="XML to PDF",
        description="Convert XML text/file into PDF document.",
        category="data-tools",
        tags=["xml", "pdf", "convert"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="csv-to-pdf",
        title="CSV to PDF",
        description="Convert CSV text/file into PDF document.",
        category="data-tools",
        tags=["csv", "pdf", "convert"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="flip-image",
        title="Flip Image",
        description="Flip image horizontally or vertically.",
        category="image-layout",
        tags=["flip", "image", "layout"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="add-border-image",
        title="Add Border Image",
        description="Add custom border size and color around an image.",
        category="image-layout",
        tags=["border", "image", "style"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="thumbnail-image",
        title="Thumbnail Image",
        description="Generate optimized thumbnail from source image.",
        category="image-layout",
        tags=["thumbnail", "image", "resize"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="image-collage",
        title="Image Collage",
        description="Create a collage using multiple uploaded images.",
        category="image-layout",
        tags=["collage", "image", "batch"],
        input_kind="mixed",
        accepts_multiple=True,
    ),
    ToolDefinition(
        slug="word-count-text",
        title="Word Count",
        description="Generate text statistics including words, sentences, and characters.",
        category="text-ops",
        tags=["word count", "text", "stats"],
        input_kind="text",
    ),
    ToolDefinition(
        slug="case-converter-text",
        title="Case Converter",
        description="Convert text to upper, lower, title, or sentence case.",
        category="text-ops",
        tags=["case", "text", "convert"],
        input_kind="text",
    ),
    ToolDefinition(
        slug="extract-keywords-text",
        title="Extract Keywords",
        description="Extract top frequent keywords from text.",
        category="text-ops",
        tags=["keywords", "text", "analysis"],
        input_kind="text",
    ),
    ToolDefinition(
        slug="slug-generator-text",
        title="Slug Generator",
        description="Generate URL-friendly slug from text.",
        category="text-ops",
        tags=["slug", "url", "text"],
        input_kind="text",
    ),
    ToolDefinition(
        slug="pdf-pages-to-zip",
        title="PDF Pages to ZIP",
        description="Export PDF pages as images packed in ZIP.",
        category="archive-lab",
        tags=["pdf", "zip", "pages"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="zip-images-to-pdf",
        title="ZIP Images to PDF",
        description="Convert image files inside ZIP into a single PDF.",
        category="archive-lab",
        tags=["zip", "images", "pdf"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="pdf-page-count",
        title="PDF Page Count",
        description="Generate page, word, and character statistics for a PDF.",
        category="pdf-insights",
        tags=["pdf", "count", "analytics"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="reverse-pdf",
        title="Reverse PDF",
        description="Reverse complete page order of a PDF document.",
        category="pdf-insights",
        tags=["pdf", "reverse", "pages"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="flatten-pdf",
        title="Flatten PDF",
        description="Flatten PDF into static pages to lock overlays and annotations.",
        category="pdf-insights",
        tags=["pdf", "flatten", "finalize"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="pdf-to-html",
        title="PDF to HTML",
        description="Export extracted PDF text into an HTML document.",
        category="pdf-insights",
        tags=["pdf", "html", "export"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="pdf-to-bmp",
        title="PDF to BMP",
        description="Render PDF pages as BMP images and package in ZIP.",
        category="pdf-insights",
        tags=["pdf", "bmp", "convert"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="pdf-to-gif",
        title="PDF to GIF",
        description="Render PDF pages as GIF images and package in ZIP.",
        category="pdf-insights",
        tags=["pdf", "gif", "convert"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="sharpen-image",
        title="Sharpen Image",
        description="Increase image sharpness by configurable factor.",
        category="image-enhance",
        tags=["image", "sharpen", "enhance"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="brighten-image",
        title="Brighten Image",
        description="Adjust image brightness by configurable factor.",
        category="image-enhance",
        tags=["image", "brightness", "enhance"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="contrast-image",
        title="Contrast Image",
        description="Adjust image contrast by configurable factor.",
        category="image-enhance",
        tags=["image", "contrast", "enhance"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="invert-image",
        title="Invert Image",
        description="Invert image colors with one click.",
        category="image-enhance",
        tags=["image", "invert", "effect"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="posterize-image",
        title="Posterize Image",
        description="Reduce color depth for stylized poster effect.",
        category="image-enhance",
        tags=["image", "posterize", "effect"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="image-histogram",
        title="Image Histogram",
        description="Extract RGB histogram summary and image stats.",
        category="image-enhance",
        tags=["image", "histogram", "analysis"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="remove-extra-spaces-text",
        title="Remove Extra Spaces",
        description="Normalize extra spaces and tabs in text.",
        category="text-cleanup",
        tags=["text", "cleanup", "spaces"],
        input_kind="text",
    ),
    ToolDefinition(
        slug="sort-lines-text",
        title="Sort Lines",
        description="Sort text lines in ascending or descending order.",
        category="text-cleanup",
        tags=["text", "sort", "lines"],
        input_kind="text",
    ),
    ToolDefinition(
        slug="deduplicate-lines-text",
        title="Deduplicate Lines",
        description="Remove duplicate lines while preserving first occurrence order.",
        category="text-cleanup",
        tags=["text", "deduplicate", "lines"],
        input_kind="text",
    ),
    ToolDefinition(
        slug="find-replace-text",
        title="Find and Replace",
        description="Find and replace text with optional case sensitivity.",
        category="text-cleanup",
        tags=["text", "find", "replace"],
        input_kind="text",
    ),
    ToolDefinition(
        slug="split-text-file",
        title="Split Text File",
        description="Split large text into multiple files by lines and download ZIP.",
        category="text-cleanup",
        tags=["text", "split", "zip"],
        input_kind="text",
    ),
    ToolDefinition(
        slug="reading-time-text",
        title="Reading Time Estimator",
        description="Estimate reading time from total words and target WPM.",
        category="text-cleanup",
        tags=["text", "reading", "time"],
        input_kind="text",
    ),
    ToolDefinition(
        slug="images-to-zip",
        title="Images to ZIP",
        description="Pack uploaded images into a single ZIP archive.",
        category="batch-automation",
        tags=["images", "zip", "batch"],
        input_kind="files",
        accepts_multiple=True,
    ),
    ToolDefinition(
        slug="batch-convert-images",
        title="Batch Convert Images",
        description="Convert multiple images into selected format and download ZIP.",
        category="batch-automation",
        tags=["images", "convert", "batch"],
        input_kind="mixed",
        accepts_multiple=True,
    ),
    ToolDefinition(
        slug="merge-text-files",
        title="Merge Text Files",
        description="Merge multiple text files into a single output document.",
        category="batch-automation",
        tags=["text", "merge", "batch"],
        input_kind="mixed",
        accepts_multiple=True,
    ),
    ToolDefinition(
        slug="json-prettify",
        title="JSON Prettify",
        description="Format minified JSON into readable pretty JSON.",
        category="batch-automation",
        tags=["json", "format", "developer"],
        input_kind="text",
    ),
    ToolDefinition(
        slug="csv-to-json",
        title="CSV to JSON",
        description="Convert CSV tabular data into JSON array format.",
        category="batch-automation",
        tags=["csv", "json", "convert"],
        input_kind="text",
    ),
    ToolDefinition(
        slug="json-to-csv",
        title="JSON to CSV",
        description="Convert JSON object/list into CSV table output.",
        category="batch-automation",
        tags=["json", "csv", "convert"],
        input_kind="text",
    ),
    ToolDefinition(
        slug="pdf-to-docx",
        title="PDF to DOCX",
        description="Convert PDF text content into editable DOCX format.",
        category="office-suite",
        tags=["pdf", "docx", "convert"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="docx-to-pdf",
        title="DOCX to PDF",
        description="Convert DOCX documents into PDF format.",
        category="office-suite",
        tags=["docx", "pdf", "convert"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="pdf-to-excel",
        title="PDF to Excel",
        description="Export PDF text lines into XLSX spreadsheet format.",
        category="office-suite",
        tags=["pdf", "excel", "xlsx"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="excel-to-pdf",
        title="Excel to PDF",
        description="Convert XLSX spreadsheets into PDF documents.",
        category="office-suite",
        tags=["excel", "xlsx", "pdf"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="pdf-to-pptx",
        title="PDF to PPTX",
        description="Convert PDF pages into editable PPTX slide content.",
        category="office-suite",
        tags=["pdf", "pptx", "slides"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="pptx-to-pdf",
        title="PPTX to PDF",
        description="Convert PPTX slide text into PDF format.",
        category="office-suite",
        tags=["pptx", "pdf", "convert"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="scan-to-pdf",
        title="Scan to PDF",
        description="Create PDF documents from scanned images or photos.",
        category="pdf-core",
        tags=["scan", "image", "pdf"],
        input_kind="files",
        accepts_multiple=True,
    ),
    ToolDefinition(
        slug="sign-pdf",
        title="Sign PDF",
        description="Add signature block text and timestamp to PDF pages.",
        category="pdf-security",
        tags=["sign", "signature", "pdf"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="edit-metadata-pdf",
        title="Edit Metadata",
        description="Update title, author, subject, and keywords for PDF files.",
        category="pdf-advanced",
        tags=["metadata", "pdf", "edit"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="pdf-to-pdfa",
        title="PDF to PDF/A",
        description="Generate archival-friendly PDF export for long-term storage.",
        category="pdf-advanced",
        tags=["pdf", "pdfa", "archive"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="chat-with-pdf",
        title="Chat with PDF",
        description="Ask questions and get context answers from PDF text.",
        category="text-ai",
        tags=["chat", "pdf", "ai"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="upscale-image",
        title="Upscale Image",
        description="Upscale image dimensions while preserving visual quality.",
        category="image-enhance",
        tags=["upscale", "image", "enhance"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="create-workflow",
        title="Create Workflow",
        description="Build reusable workflow JSON from your favorite tool steps.",
        category="utility",
        tags=["workflow", "automation", "json"],
        input_kind="text",
    ),
    ToolDefinition(
        slug="add-image-pdf",
        title="Add Image to PDF",
        description="Overlay an image logo or stamp onto PDF pages.",
        category="page-ops",
        tags=["image", "pdf", "overlay"],
        input_kind="mixed",
        accepts_multiple=True,
    ),
    ToolDefinition(
        slug="ocr-image",
        title="OCR Image",
        description="Extract readable text from scanned or photographed images.",
        category="ocr-vision",
        tags=["ocr", "image", "text"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="ocr-pdf",
        title="OCR PDF",
        description="Extract text from scanned PDF pages and generate a searchable PDF output.",
        category="ocr-vision",
        tags=["ocr", "pdf", "scan"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="remove-background",
        title="Remove Background",
        description="Remove image backgrounds and export a transparent PNG cutout.",
        category="ocr-vision",
        tags=["background", "image", "ai"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="blur-face",
        title="Blur Face",
        description="Detect faces in images and blur them for privacy-safe sharing.",
        category="ocr-vision",
        tags=["face", "blur", "privacy"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="pixelate-face",
        title="Pixelate Face",
        description="Detect faces and pixelate them for stronger privacy masking.",
        category="ocr-vision",
        tags=["face", "pixelate", "privacy"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="blur-background",
        title="Blur Background",
        description="Keep the main subject readable while softly blurring the background.",
        category="ocr-vision",
        tags=["background", "blur", "portrait"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="add-text-image",
        title="Add Text to Image",
        description="Place headlines, labels, names, or captions directly onto images.",
        category="image-layout",
        tags=["text", "image", "caption"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="add-logo-image",
        title="Add Logo to Image",
        description="Upload the base image first and logo second to create branded image overlays.",
        category="image-layout",
        tags=["logo", "image", "overlay"],
        input_kind="files",
        accepts_multiple=True,
    ),
    ToolDefinition(
        slug="join-images",
        title="Join Images",
        description="Combine multiple images into one horizontal or vertical layout.",
        category="image-layout",
        tags=["join", "merge", "image"],
        input_kind="files",
        accepts_multiple=True,
    ),
    ToolDefinition(
        slug="split-image",
        title="Split Image",
        description="Split a single image into a tile grid and download every part at once.",
        category="image-layout",
        tags=["split", "tiles", "image"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="circle-crop-image",
        title="Circle Crop Image",
        description="Create a clean circular crop with transparent corners for profile-ready assets.",
        category="image-layout",
        tags=["circle", "crop", "image"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="square-crop-image",
        title="Square Crop Image",
        description="Center-crop any image into a perfect square for social and profile use.",
        category="image-layout",
        tags=["square", "crop", "image"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="image-color-picker",
        title="Image Color Picker",
        description="Extract the dominant colors from an image with palette preview and JSON export.",
        category="image-enhance",
        tags=["color", "palette", "image"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="motion-blur-image",
        title="Motion Blur Image",
        description="Apply cinematic horizontal or vertical motion blur to photos and graphics.",
        category="image-enhance",
        tags=["motion", "blur", "image"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="pdf-to-tiff",
        title="PDF to TIFF",
        description="Convert PDF pages into a TIFF document for scanning and archive workflows.",
        category="vector-lab",
        tags=["pdf", "tiff", "convert"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="tiff-to-pdf",
        title="TIFF to PDF",
        description="Convert TIFF images into PDF documents.",
        category="vector-lab",
        tags=["tiff", "pdf", "convert"],
        input_kind="files",
        accepts_multiple=True,
    ),
    ToolDefinition(
        slug="pdf-to-svg",
        title="PDF to SVG",
        description="Export each PDF page into SVG vector files.",
        category="vector-lab",
        tags=["pdf", "svg", "vector"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="svg-to-pdf",
        title="SVG to PDF",
        description="Convert one or more SVG assets into PDF output.",
        category="vector-lab",
        tags=["svg", "pdf", "vector"],
        input_kind="files",
        accepts_multiple=True,
    ),
    ToolDefinition(
        slug="pdf-to-rtf",
        title="PDF to RTF",
        description="Convert PDF text content into rich text format.",
        category="ebook-convert",
        tags=["pdf", "rtf", "convert"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="rtf-to-pdf",
        title="RTF to PDF",
        description="Convert RTF documents into PDF format.",
        category="ebook-convert",
        tags=["rtf", "pdf", "convert"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="pdf-to-odt",
        title="PDF to ODT",
        description="Convert PDF text into OpenDocument Text format.",
        category="ebook-convert",
        tags=["pdf", "odt", "convert"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="odt-to-pdf",
        title="ODT to PDF",
        description="Convert OpenDocument Text files into PDF documents.",
        category="ebook-convert",
        tags=["odt", "pdf", "convert"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="pdf-to-epub",
        title="PDF to EPUB",
        description="Convert PDF text into EPUB eBook format.",
        category="ebook-convert",
        tags=["pdf", "epub", "ebook"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="epub-to-pdf",
        title="EPUB to PDF",
        description="Convert EPUB eBooks into PDF output.",
        category="ebook-convert",
        tags=["epub", "pdf", "ebook"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="optimize-pdf",
        title="Optimize PDF",
        description="Reduce PDF size with stronger optimization defaults for lighter downloads.",
        category="pdf-core",
        tags=["pdf", "optimize", "compress"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="convert-to-pdf",
        title="Convert to PDF",
        description="Upload supported documents, images, or eBooks and convert them into PDF.",
        category="office-suite",
        tags=["convert", "pdf", "generic"],
        input_kind="files",
        accepts_multiple=True,
    ),
    ToolDefinition(
        slug="convert-from-pdf",
        title="Convert from PDF",
        description="Export PDF files into the format you choose from one unified tool.",
        category="office-suite",
        tags=["convert", "pdf", "export"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="pdf-converter",
        title="PDF Converter",
        description="Smart converter that handles PDF export or PDF generation depending on the input file.",
        category="office-suite",
        tags=["pdf", "converter", "smart"],
        input_kind="mixed",
        accepts_multiple=True,
    ),
    ToolDefinition(
        slug="pdf-security",
        title="PDF Security",
        description="Protect or unlock PDF files from one shared security workspace.",
        category="pdf-security",
        tags=["pdf", "security", "password"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="ai-summarizer",
        title="AI Summarizer",
        description="Generate concise summaries from PDFs or pasted text content.",
        category="text-ai",
        tags=["summary", "ai", "text"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="pdf-viewer",
        title="PDF Viewer",
        description="Inspect page count, metadata, and preview text from uploaded PDFs.",
        category="text-ai",
        tags=["pdf", "viewer", "preview"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="pdf-intelligence",
        title="PDF Intelligence",
        description="Generate summary, keyword, and content analytics for PDF documents.",
        category="text-ai",
        tags=["pdf", "intelligence", "analytics"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="edit-pdf",
        title="Edit PDF",
        description="Add text, watermark, highlight, annotations, or images from one editing page.",
        category="page-ops",
        tags=["edit", "pdf", "annotate"],
        input_kind="mixed",
        accepts_multiple=True,
    ),
    ToolDefinition(
        slug="annotate-pdf",
        title="Annotate PDF",
        description="Place free-text annotations onto specific PDF pages.",
        category="page-ops",
        tags=["annotate", "pdf", "notes"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="highlight-pdf",
        title="Highlight PDF",
        description="Apply visible highlight blocks to important areas inside a PDF page.",
        category="page-ops",
        tags=["highlight", "pdf", "review"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="pdf-filler",
        title="PDF Filler",
        description="Fill PDF areas with typed text at the coordinates you choose.",
        category="page-ops",
        tags=["fill", "pdf", "form"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="remove-pages",
        title="Remove Pages",
        description="Delete selected pages from a PDF file using the page list you provide.",
        category="page-ops",
        tags=["remove", "pages", "pdf"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="add-page-numbers",
        title="Add Page Numbers",
        description="Add page numbers from a dedicated quick-access tool page.",
        category="page-ops",
        tags=["page numbers", "pdf", "pages"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="add-watermark",
        title="Add Watermark",
        description="Apply text-based watermark overlays to PDF pages.",
        category="page-ops",
        tags=["watermark", "pdf", "branding"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="pdf-ocr",
        title="PDF OCR",
        description="Convert scanned PDF pages into searchable text-based PDF output.",
        category="ocr-vision",
        tags=["pdf", "ocr", "scan"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="image-to-text",
        title="Image to Text",
        description="Run OCR on images and extract their readable text.",
        category="ocr-vision",
        tags=["image", "ocr", "text"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="jpg-to-text",
        title="JPG to Text",
        description="Extract readable text from JPG and JPEG images.",
        category="ocr-vision",
        tags=["jpg", "ocr", "text"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="png-to-text",
        title="PNG to Text",
        description="Extract readable text from PNG images.",
        category="ocr-vision",
        tags=["png", "ocr", "text"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="check-image-dpi",
        title="Check Image DPI",
        description="Inspect the current DPI and dimensions stored in an image file.",
        category="image-enhance",
        tags=["dpi", "image", "analyze"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="convert-dpi",
        title="Convert DPI",
        description="Rewrite image DPI metadata for printing or document upload requirements.",
        category="image-enhance",
        tags=["dpi", "image", "convert"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="resize-image-in-cm",
        title="Resize Image in CM",
        description="Resize images using centimeter dimensions and a selected DPI.",
        category="image-layout",
        tags=["resize", "cm", "image"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="resize-image-in-mm",
        title="Resize Image in MM",
        description="Resize images using millimeter dimensions and a selected DPI.",
        category="image-layout",
        tags=["resize", "mm", "image"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="resize-image-in-inch",
        title="Resize Image in Inches",
        description="Resize images using inch dimensions and a selected DPI.",
        category="image-layout",
        tags=["resize", "inch", "image"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="add-name-dob-image",
        title="Add Name and DOB on Photo",
        description="Overlay a name and date of birth onto an uploaded photo.",
        category="image-layout",
        tags=["name", "dob", "photo"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="merge-photo-signature",
        title="Merge Photo and Signature",
        description="Combine a photo and signature into one clean export.",
        category="image-layout",
        tags=["photo", "signature", "merge"],
        input_kind="files",
        accepts_multiple=True,
    ),
    ToolDefinition(
        slug="black-and-white-image",
        title="Black and White Image",
        description="Turn a color image into a high-contrast black and white result.",
        category="image-enhance",
        tags=["black", "white", "image"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="censor-photo",
        title="Censor Photo",
        description="Censor face regions when detected, or pixelate the full photo as a fallback.",
        category="ocr-vision",
        tags=["censor", "privacy", "image"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="picture-to-pixel-art",
        title="Picture to Pixel Art",
        description="Turn photos into chunky pixel-art style graphics.",
        category="image-enhance",
        tags=["pixel art", "image", "effect"],
        input_kind="mixed",
    ),
    ToolDefinition(
        slug="generate-signature",
        title="Generate Signature",
        description="Create a transparent signature image from typed text.",
        category="image-layout",
        tags=["signature", "text", "image"],
        input_kind="text",
    ),
    ToolDefinition(
        slug="word-to-pdf",
        title="Word to PDF",
        description="Convert Word documents into PDF format.",
        category="office-suite",
        tags=["word", "docx", "pdf"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="pdf-to-word",
        title="PDF to Word",
        description="Convert PDF content into editable Word documents.",
        category="office-suite",
        tags=["pdf", "word", "docx"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="powerpoint-to-pdf",
        title="PowerPoint to PDF",
        description="Convert PowerPoint slide decks into PDF output.",
        category="office-suite",
        tags=["powerpoint", "pptx", "pdf"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="pdf-to-powerpoint",
        title="PDF to PowerPoint",
        description="Convert PDF pages into editable PowerPoint slide output.",
        category="office-suite",
        tags=["pdf", "powerpoint", "pptx"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="eml-to-pdf",
        title="EML to PDF",
        description="Convert email message files into PDF documents.",
        category="format-lab",
        tags=["eml", "email", "pdf"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="fb2-to-pdf",
        title="FB2 to PDF",
        description="Convert FB2 eBook files into PDF output.",
        category="ebook-convert",
        tags=["fb2", "ebook", "pdf"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="cbz-to-pdf",
        title="CBZ to PDF",
        description="Convert comic-book ZIP image archives into PDF documents.",
        category="ebook-convert",
        tags=["cbz", "comic", "pdf"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="ebook-to-pdf",
        title="eBook to PDF",
        description="Convert supported eBook uploads like EPUB, FB2, and CBZ into PDF.",
        category="ebook-convert",
        tags=["ebook", "pdf", "convert"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="heic-to-pdf",
        title="HEIC to PDF",
        description="Convert HEIC images into PDF documents.",
        category="format-lab",
        tags=["heic", "image", "pdf"],
        input_kind="files",
        accepts_multiple=True,
    ),
    ToolDefinition(
        slug="heif-to-pdf",
        title="HEIF to PDF",
        description="Convert HEIF images into PDF documents.",
        category="format-lab",
        tags=["heif", "image", "pdf"],
        input_kind="files",
        accepts_multiple=True,
    ),
    ToolDefinition(
        slug="jfif-to-pdf",
        title="JFIF to PDF",
        description="Convert JFIF images into PDF documents.",
        category="format-lab",
        tags=["jfif", "image", "pdf"],
        input_kind="files",
        accepts_multiple=True,
    ),
    ToolDefinition(
        slug="zip-to-pdf",
        title="ZIP to PDF",
        description="Convert ZIP archives of ordered images into a single PDF.",
        category="archive-lab",
        tags=["zip", "images", "pdf"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="cbr-to-pdf",
        title="CBR to PDF",
        description="Convert CBR comic book archives (RAR/ZIP) into a single PDF.",
        category="archive-lab",
        tags=["cbr", "comic", "pdf", "rar"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="djvu-to-pdf",
        title="DjVu to PDF",
        description="Convert DjVu documents into PDF format.",
        category="format-lab",
        tags=["djvu", "pdf", "convert"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="ai-to-pdf",
        title="AI to PDF",
        description="Convert Adobe Illustrator AI files into PDF documents.",
        category="format-lab",
        tags=["ai", "illustrator", "pdf", "convert"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="pdf-to-mobi",
        title="PDF to MOBI",
        description="Convert PDF documents into MOBI format for e-readers.",
        category="ebook-convert",
        tags=["pdf", "mobi", "ebook", "kindle"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="mobi-to-pdf",
        title="MOBI to PDF",
        description="Convert MOBI e-books into PDF documents.",
        category="ebook-convert",
        tags=["mobi", "pdf", "ebook", "kindle"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="xps-to-pdf",
        title="XPS to PDF",
        description="Convert XPS documents into PDF format.",
        category="format-lab",
        tags=["xps", "pdf", "convert", "microsoft"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="wps-to-pdf",
        title="WPS to PDF",
        description="Convert WPS Office documents into PDF format.",
        category="office-suite",
        tags=["wps", "pdf", "office", "convert"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="dwg-to-pdf",
        title="DWG to PDF",
        description="Convert AutoCAD DWG drawings into PDF documents.",
        category="vector-lab",
        tags=["dwg", "autocad", "pdf", "cad"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="pub-to-pdf",
        title="PUB to PDF",
        description="Convert Microsoft Publisher PUB files into PDF format.",
        category="document-convert",
        tags=["pub", "publisher", "pdf", "convert"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="hwp-to-pdf",
        title="HWP to PDF",
        description="Convert Hangul HWP documents into PDF format.",
        category="format-lab",
        tags=["hwp", "hangul", "pdf", "korean"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="chm-to-pdf",
        title="CHM to PDF",
        description="Convert Windows CHM help files into PDF documents.",
        category="format-lab",
        tags=["chm", "help", "pdf", "convert"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="dxf-to-pdf",
        title="DXF to PDF",
        description="Convert AutoCAD DXF drawings into PDF documents.",
        category="vector-lab",
        tags=["dxf", "autocad", "pdf", "cad", "vector"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="pages-to-pdf",
        title="PAGES to PDF",
        description="Convert Apple Pages documents into PDF format.",
        category="format-lab",
        tags=["pages", "apple", "pdf", "mac"],
        input_kind="files",
    ),
    ToolDefinition(
        slug="html-to-image",
        title="HTML to Image",
        description="Convert HTML content or web page URL into a JPG or PNG image.",
        category="image-core",
        tags=["html", "image", "convert", "screenshot"],
        input_kind="mixed",
    ),
]

TOOL_SLUGS = {tool.slug for tool in TOOLS}
